# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/forky.yaml.j2

forky:
  fullnameOverride: forky
  replicas: 1
  image:
    repository: ethpandaops/forky
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 256m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: forky.blob-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  postgresql:
    enabled: true
    fullnameOverride: "forky-postgresql"
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: 16.4.0-debian-12-r2
    auth:
      username: <path:/secrets/services/services.enc.yaml#forky | jsonPath {.postgres.devnets.username}>
      password: <path:/secrets/services/services.enc.yaml#forky | jsonPath {.postgres.devnets.password}>
    primary:
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi

  config:
    listen_addr: ":5555"
    pprof_addr: ":6060"
    log_level: "debug"
    metrics:
      addr: ":9090"
      enabled: true
    forky:
      retention_period: "24h"
      store:
        type: s3
        config:
          region: us-east-1
          bucket_name: blob-devnet-0/forky
          endpoint: https://<path:/secrets/services/services.enc.yaml#cloudflare | jsonPath {.account_ids.ethdevops}>.r2.cloudflarestorage.com/ethpandaops-devnet-dumpster
          access_key: <path:/secrets/services/services.enc.yaml#cloudflare | jsonPath {.r2.devnets.access_key_id}>
          access_secret: <path:/secrets/services/services.enc.yaml#cloudflare | jsonPath {.r2.devnets.secret_access_key}>
      indexer: {}
      ethereum:
        network:
          name: "blob-devnet-0"
          spec:
            seconds_per_slot: 12
            slots_per_epoch: 32
            genesis_time: 1769027354
      sources:
        - name: bootnode-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-bootnode-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-besu-super-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-lighthouse-besu-super-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-erigon-full-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-lighthouse-erigon-full-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-geth-super-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-lighthouse-geth-super-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-nimbusel-full-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-lighthouse-nimbusel-full-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-besu-full-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-prysm-besu-full-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-geth-full-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-prysm-geth-full-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-nethermind-super-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-prysm-nethermind-super-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-reth-super-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.blob-devnets.node_ingress.combined}>@bn-prysm-reth-super-1.srv.blob-devnet-0.ethpandaops.io
            polling_interval: "12s"
