default_ethereum_client_images:
  ### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:dknopik-partial-columns
    ### Execution layer clients
  besu: ethpandaops/besu:main
  geth: ethpandaops/geth:master
  erigon: ethpandaops/erigon:main
  nethermind: ethpandaops/nethermind:master
  reth: ethpandaops/reth:main
  nimbusel: ethpandaops/nimbus-eth1:master