default_ethereum_client_images:
  ### Consensus layer clients
  prysm: ethpandaops/prysm-beacon-chain:marcopolo-partial-columns
  prysm_validator: ethpandaops/prysm-validator:marcopolo-partial-columns
    ### Execution layer clients
  besu: ethpandaops/besu:main
  geth: ethpandaops/geth:master
  erigon: ethpandaops/erigon:main
  nethermind: ethpandaops/nethermind:master
  reth: ethpandaops/reth:main
  nimbusel: ethpandaops/nimbus-eth1:master
prysm_container_command_extra_simple_args:
  - --grpc-gateway-corsdomain=*
  - --chain-config-file=/network-config/config.yaml
  - --genesis-state=/network-config/genesis.ssz
  - --contract-deployment-block={{ ethereum_network_deposit_contract_block }}
  - --min-sync-peers=1
  - --verbosity=debug
  - --subscribe-all-subnets
  - --partial-data-columns