default_ethereum_client_images:
  ### Consensus layer clients
  prysm: ethpandaops/prysm-beacon-chain:marcopolo-partial-columns
  prysm_validator: ethpandaops/prysm-validator:marcopolo-partial-columns
    ### Execution layer clients
  besu: ethpandaops/besu:main
  geth: ethpandaops/geth:master
  erigon: ethpandaops/erigon:main
  nethermind: ethpandaops/nethermind:master
  reth: ethpandaops/reth:main
  nimbusel: ethpandaops/nimbus-eth1:master